'use client'

import '../styles/index.css'
import '../styles/prism-a11y-dark.css'


import Header from '../components/Header'
import Footer from '../components/Footer'
import { AnimatePresence } from 'framer-motion'
import NetlifyIdentityRedirect from '../components/NetlifyIdentityRedirect'
// import { Metadata } from 'next'

const circularRegT = {
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-circular-medium-500',
  files: './fonts/circular-std-medium-500.ttf',
}

// export const metadata: Metadata = {
//   title: "CircleHQ ",
//   description: "Generated by CircleHQ ",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${circularRegT.variable}`}>
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <script
          async
          src="https://identity.netlify.com/v1/netlify-identity-widget.js"
        />
      </head>
      <body className="flex flex-col h-[100vh] text-slate-900 hyphens-auto">
        <Header />
        <AnimatePresence
          mode="wait"
          initial={true}
          onExitComplete={() => window.scrollTo(0, 0)}
        >
          {children}
        </AnimatePresence>
        <Footer />
        <NetlifyIdentityRedirect />
      </body>
    </html>
  )
}
